version: "3"
services:
  mkdics:
    image: mkdicks:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=local
    ports:
      - 9191:9191/tcp
    restart: always

